<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>AnyCPU;x64</Platforms>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <IsPackable>false</IsPackable>
    <Description>Networking and protocol infrastructure for OPNX systems, including TCP, named pipes, shared memory, framing, packets, and connection-oriented communication.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OPNX.Lib.Common\OPNX.Lib.Common.csproj" />
  </ItemGroup>

</Project>
