<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
    <EnableLibraryImportGenerator>true</EnableLibraryImportGenerator>
    <IsPackable>false</IsPackable>
    <Description>Media processing infrastructure for OPNX systems, including FFmpeg, OpenCV, and SkiaSharp-based encoding, decoding, conversion, filtering, muxing, and media data handling.</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.13.0.20260427" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OPNX.Lib.Common\OPNX.Lib.Common.csproj" />
  </ItemGroup>

</Project>
