<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <Platforms>AnyCPU;x64</Platforms>
    <EnableLibraryImportGenerator>true</EnableLibraryImportGenerator>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FFmpeg.AutoGen" Version="8.0.0" />
    <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\OPNX.Lib.Common\OPNX.Lib.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="FFMpeg\Lib\x64\avcodec-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\avdevice-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\avfilter-11.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\avformat-62.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\avutil-60.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\swresample-6.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="FFMpeg\Lib\x64\swscale-9.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
